// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
	"github.com/cloudreve/Cloudreve/v4/ent/useridentity"
)

// UserIdentityCreate is the builder for creating a UserIdentity entity.
type UserIdentityCreate struct {
	config
	mutation *UserIdentityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (uic *UserIdentityCreate) SetCreatedAt(t time.Time) *UserIdentityCreate {
	uic.mutation.SetCreatedAt(t)
	return uic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uic *UserIdentityCreate) SetNillableCreatedAt(t *time.Time) *UserIdentityCreate {
	if t != nil {
		uic.SetCreatedAt(*t)
	}
	return uic
}

// SetUpdatedAt sets the "updated_at" field.
func (uic *UserIdentityCreate) SetUpdatedAt(t time.Time) *UserIdentityCreate {
	uic.mutation.SetUpdatedAt(t)
	return uic
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (uic *UserIdentityCreate) SetNillableUpdatedAt(t *time.Time) *UserIdentityCreate {
	if t != nil {
		uic.SetUpdatedAt(*t)
	}
	return uic
}

// SetDeletedAt sets the "deleted_at" field.
func (uic *UserIdentityCreate) SetDeletedAt(t time.Time) *UserIdentityCreate {
	uic.mutation.SetDeletedAt(t)
	return uic
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (uic *UserIdentityCreate) SetNillableDeletedAt(t *time.Time) *UserIdentityCreate {
	if t != nil {
		uic.SetDeletedAt(*t)
	}
	return uic
}

// SetUserID sets the "user_id" field.
func (uic *UserIdentityCreate) SetUserID(i int) *UserIdentityCreate {
	uic.mutation.SetUserID(i)
	return uic
}

// SetProvider sets the "provider" field.
func (uic *UserIdentityCreate) SetProvider(s string) *UserIdentityCreate {
	uic.mutation.SetProvider(s)
	return uic
}

// SetIssuer sets the "issuer" field.
func (uic *UserIdentityCreate) SetIssuer(s string) *UserIdentityCreate {
	uic.mutation.SetIssuer(s)
	return uic
}

// SetSubject sets the "subject" field.
func (uic *UserIdentityCreate) SetSubject(s string) *UserIdentityCreate {
	uic.mutation.SetSubject(s)
	return uic
}

// SetEmail sets the "email" field.
func (uic *UserIdentityCreate) SetEmail(s string) *UserIdentityCreate {
	uic.mutation.SetEmail(s)
	return uic
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (uic *UserIdentityCreate) SetNillableEmail(s *string) *UserIdentityCreate {
	if s != nil {
		uic.SetEmail(*s)
	}
	return uic
}

// SetEmailVerified sets the "email_verified" field.
func (uic *UserIdentityCreate) SetEmailVerified(b bool) *UserIdentityCreate {
	uic.mutation.SetEmailVerified(b)
	return uic
}

// SetNillableEmailVerified sets the "email_verified" field if the given value is not nil.
func (uic *UserIdentityCreate) SetNillableEmailVerified(b *bool) *UserIdentityCreate {
	if b != nil {
		uic.SetEmailVerified(*b)
	}
	return uic
}

// SetName sets the "name" field.
func (uic *UserIdentityCreate) SetName(s string) *UserIdentityCreate {
	uic.mutation.SetName(s)
	return uic
}

// SetNillableName sets the "name" field if the given value is not nil.
func (uic *UserIdentityCreate) SetNillableName(s *string) *UserIdentityCreate {
	if s != nil {
		uic.SetName(*s)
	}
	return uic
}

// SetAvatar sets the "avatar" field.
func (uic *UserIdentityCreate) SetAvatar(s string) *UserIdentityCreate {
	uic.mutation.SetAvatar(s)
	return uic
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (uic *UserIdentityCreate) SetNillableAvatar(s *string) *UserIdentityCreate {
	if s != nil {
		uic.SetAvatar(*s)
	}
	return uic
}

// SetUser sets the "user" edge to the User entity.
func (uic *UserIdentityCreate) SetUser(u *User) *UserIdentityCreate {
	return uic.SetUserID(u.ID)
}

// Mutation returns the UserIdentityMutation object of the builder.
func (uic *UserIdentityCreate) Mutation() *UserIdentityMutation {
	return uic.mutation
}

// Save creates the UserIdentity in the database.
func (uic *UserIdentityCreate) Save(ctx context.Context) (*UserIdentity, error) {
	if err := uic.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, uic.sqlSave, uic.mutation, uic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uic *UserIdentityCreate) SaveX(ctx context.Context) *UserIdentity {
	v, err := uic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uic *UserIdentityCreate) Exec(ctx context.Context) error {
	_, err := uic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uic *UserIdentityCreate) ExecX(ctx context.Context) {
	if err := uic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uic *UserIdentityCreate) defaults() error {
	if _, ok := uic.mutation.CreatedAt(); !ok {
		if useridentity.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized useridentity.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := useridentity.DefaultCreatedAt()
		uic.mutation.SetCreatedAt(v)
	}
	if _, ok := uic.mutation.UpdatedAt(); !ok {
		if useridentity.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized useridentity.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := useridentity.DefaultUpdatedAt()
		uic.mutation.SetUpdatedAt(v)
	}
	if _, ok := uic.mutation.EmailVerified(); !ok {
		v := useridentity.DefaultEmailVerified
		uic.mutation.SetEmailVerified(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (uic *UserIdentityCreate) check() error {
	if _, ok := uic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserIdentity.created_at"`)}
	}
	if _, ok := uic.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserIdentity.updated_at"`)}
	}
	if _, ok := uic.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserIdentity.user_id"`)}
	}
	if _, ok := uic.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "UserIdentity.provider"`)}
	}
	if _, ok := uic.mutation.Issuer(); !ok {
		return &ValidationError{Name: "issuer", err: errors.New(`ent: missing required field "UserIdentity.issuer"`)}
	}
	if _, ok := uic.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "UserIdentity.subject"`)}
	}
	if _, ok := uic.mutation.EmailVerified(); !ok {
		return &ValidationError{Name: "email_verified", err: errors.New(`ent: missing required field "UserIdentity.email_verified"`)}
	}
	if _, ok := uic.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserIdentity.user"`)}
	}
	return nil
}

func (uic *UserIdentityCreate) sqlSave(ctx context.Context) (*UserIdentity, error) {
	if err := uic.check(); err != nil {
		return nil, err
	}
	_node, _spec := uic.createSpec()
	if err := sqlgraph.CreateNode(ctx, uic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	uic.mutation.id = &_node.ID
	uic.mutation.done = true
	return _node, nil
}

func (uic *UserIdentityCreate) createSpec() (*UserIdentity, *sqlgraph.CreateSpec) {
	var (
		_node = &UserIdentity{config: uic.config}
		_spec = sqlgraph.NewCreateSpec(useridentity.Table, sqlgraph.NewFieldSpec(useridentity.FieldID, field.TypeInt))
	)

	if id, ok := uic.mutation.ID(); ok {
		_node.ID = id
		id64 := int64(id)
		_spec.ID.Value = id64
	}

	_spec.OnConflict = uic.conflict
	if value, ok := uic.mutation.CreatedAt(); ok {
		_spec.SetField(useridentity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := uic.mutation.UpdatedAt(); ok {
		_spec.SetField(useridentity.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := uic.mutation.DeletedAt(); ok {
		_spec.SetField(useridentity.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := uic.mutation.Provider(); ok {
		_spec.SetField(useridentity.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := uic.mutation.Issuer(); ok {
		_spec.SetField(useridentity.FieldIssuer, field.TypeString, value)
		_node.Issuer = value
	}
	if value, ok := uic.mutation.Subject(); ok {
		_spec.SetField(useridentity.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := uic.mutation.Email(); ok {
		_spec.SetField(useridentity.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := uic.mutation.EmailVerified(); ok {
		_spec.SetField(useridentity.FieldEmailVerified, field.TypeBool, value)
		_node.EmailVerified = value
	}
	if value, ok := uic.mutation.Name(); ok {
		_spec.SetField(useridentity.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := uic.mutation.Avatar(); ok {
		_spec.SetField(useridentity.FieldAvatar, field.TypeString, value)
		_node.Avatar = value
	}
	if nodes := uic.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useridentity.UserTable,
			Columns: []string{useridentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserIdentity.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserIdentityUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (uic *UserIdentityCreate) OnConflict(opts ...sql.ConflictOption) *UserIdentityUpsertOne {
	uic.conflict = opts
	return &UserIdentityUpsertOne{
		create: uic,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserIdentity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (uic *UserIdentityCreate) OnConflictColumns(columns ...string) *UserIdentityUpsertOne {
	uic.conflict = append(uic.conflict, sql.ConflictColumns(columns...))
	return &UserIdentityUpsertOne{
		create: uic,
	}
}

type (
	// UserIdentityUpsertOne is the builder for "upsert"-ing
	//  one UserIdentity node.
	UserIdentityUpsertOne struct {
		create *UserIdentityCreate
	}

	// UserIdentityUpsert is the "OnConflict" setter.
	UserIdentityUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserIdentityUpsert) SetUpdatedAt(v time.Time) *UserIdentityUpsert {
	u.Set(useridentity.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserIdentityUpsert) UpdateUpdatedAt() *UserIdentityUpsert {
	u.SetExcluded(useridentity.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserIdentityUpsert) SetDeletedAt(v time.Time) *UserIdentityUpsert {
	u.Set(useridentity.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserIdentityUpsert) UpdateDeletedAt() *UserIdentityUpsert {
	u.SetExcluded(useridentity.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserIdentityUpsert) ClearDeletedAt() *UserIdentityUpsert {
	u.SetNull(useridentity.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserIdentityUpsert) SetUserID(v int) *UserIdentityUpsert {
	u.Set(useridentity.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserIdentityUpsert) UpdateUserID() *UserIdentityUpsert {
	u.SetExcluded(useridentity.FieldUserID)
	return u
}

// SetProvider sets the "provider" field.
func (u *UserIdentityUpsert) SetProvider(v string) *UserIdentityUpsert {
	u.Set(useridentity.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *UserIdentityUpsert) UpdateProvider() *UserIdentityUpsert {
	u.SetExcluded(useridentity.FieldProvider)
	return u
}

// SetIssuer sets the "issuer" field.
func (u *UserIdentityUpsert) SetIssuer(v string) *UserIdentityUpsert {
	u.Set(useridentity.FieldIssuer, v)
	return u
}

// UpdateIssuer sets the "issuer" field to the value that was provided on create.
func (u *UserIdentityUpsert) UpdateIssuer() *UserIdentityUpsert {
	u.SetExcluded(useridentity.FieldIssuer)
	return u
}

// SetSubject sets the "subject" field.
func (u *UserIdentityUpsert) SetSubject(v string) *UserIdentityUpsert {
	u.Set(useridentity.FieldSubject, v)
	return u
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *UserIdentityUpsert) UpdateSubject() *UserIdentityUpsert {
	u.SetExcluded(useridentity.FieldSubject)
	return u
}

// SetEmail sets the "email" field.
func (u *UserIdentityUpsert) SetEmail(v string) *UserIdentityUpsert {
	u.Set(useridentity.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *UserIdentityUpsert) UpdateEmail() *UserIdentityUpsert {
	u.SetExcluded(useridentity.FieldEmail)
	return u
}

// ClearEmail clears the value of the "email" field.
func (u *UserIdentityUpsert) ClearEmail() *UserIdentityUpsert {
	u.SetNull(useridentity.FieldEmail)
	return u
}

// SetEmailVerified sets the "email_verified" field.
func (u *UserIdentityUpsert) SetEmailVerified(v bool) *UserIdentityUpsert {
	u.Set(useridentity.FieldEmailVerified, v)
	return u
}

// UpdateEmailVerified sets the "email_verified" field to the value that was provided on create.
func (u *UserIdentityUpsert) UpdateEmailVerified() *UserIdentityUpsert {
	u.SetExcluded(useridentity.FieldEmailVerified)
	return u
}

// SetName sets the "name" field.
func (u *UserIdentityUpsert) SetName(v string) *UserIdentityUpsert {
	u.Set(useridentity.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UserIdentityUpsert) UpdateName() *UserIdentityUpsert {
	u.SetExcluded(useridentity.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *UserIdentityUpsert) ClearName() *UserIdentityUpsert {
	u.SetNull(useridentity.FieldName)
	return u
}

// SetAvatar sets the "avatar" field.
func (u *UserIdentityUpsert) SetAvatar(v string) *UserIdentityUpsert {
	u.Set(useridentity.FieldAvatar, v)
	return u
}

// UpdateAvatar sets the "avatar" field to the value that was provided on create.
func (u *UserIdentityUpsert) UpdateAvatar() *UserIdentityUpsert {
	u.SetExcluded(useridentity.FieldAvatar)
	return u
}

// ClearAvatar clears the value of the "avatar" field.
func (u *UserIdentityUpsert) ClearAvatar() *UserIdentityUpsert {
	u.SetNull(useridentity.FieldAvatar)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserIdentity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserIdentityUpsertOne) UpdateNewValues() *UserIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(useridentity.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserIdentity.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserIdentityUpsertOne) Ignore() *UserIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserIdentityUpsertOne) DoNothing() *UserIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserIdentityCreate.OnConflict
// documentation for more info.
func (u *UserIdentityUpsertOne) Update(set func(*UserIdentityUpsert)) *UserIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserIdentityUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserIdentityUpsertOne) SetUpdatedAt(v time.Time) *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserIdentityUpsertOne) UpdateUpdatedAt() *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserIdentityUpsertOne) SetDeletedAt(v time.Time) *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserIdentityUpsertOne) UpdateDeletedAt() *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserIdentityUpsertOne) ClearDeletedAt() *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserIdentityUpsertOne) SetUserID(v int) *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserIdentityUpsertOne) UpdateUserID() *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.UpdateUserID()
	})
}

// SetProvider sets the "provider" field.
func (u *UserIdentityUpsertOne) SetProvider(v string) *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *UserIdentityUpsertOne) UpdateProvider() *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.UpdateProvider()
	})
}

// SetIssuer sets the "issuer" field.
func (u *UserIdentityUpsertOne) SetIssuer(v string) *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.SetIssuer(v)
	})
}

// UpdateIssuer sets the "issuer" field to the value that was provided on create.
func (u *UserIdentityUpsertOne) UpdateIssuer() *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.UpdateIssuer()
	})
}

// SetSubject sets the "subject" field.
func (u *UserIdentityUpsertOne) SetSubject(v string) *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *UserIdentityUpsertOne) UpdateSubject() *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.UpdateSubject()
	})
}

// SetEmail sets the "email" field.
func (u *UserIdentityUpsertOne) SetEmail(v string) *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *UserIdentityUpsertOne) UpdateEmail() *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.UpdateEmail()
	})
}

// ClearEmail clears the value of the "email" field.
func (u *UserIdentityUpsertOne) ClearEmail() *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.ClearEmail()
	})
}

// SetEmailVerified sets the "email_verified" field.
func (u *UserIdentityUpsertOne) SetEmailVerified(v bool) *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.SetEmailVerified(v)
	})
}

// UpdateEmailVerified sets the "email_verified" field to the value that was provided on create.
func (u *UserIdentityUpsertOne) UpdateEmailVerified() *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.UpdateEmailVerified()
	})
}

// SetName sets the "name" field.
func (u *UserIdentityUpsertOne) SetName(v string) *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UserIdentityUpsertOne) UpdateName() *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *UserIdentityUpsertOne) ClearName() *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.ClearName()
	})
}

// SetAvatar sets the "avatar" field.
func (u *UserIdentityUpsertOne) SetAvatar(v string) *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.SetAvatar(v)
	})
}

// UpdateAvatar sets the "avatar" field to the value that was provided on create.
func (u *UserIdentityUpsertOne) UpdateAvatar() *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.UpdateAvatar()
	})
}

// ClearAvatar clears the value of the "avatar" field.
func (u *UserIdentityUpsertOne) ClearAvatar() *UserIdentityUpsertOne {
	return u.Update(func(s *UserIdentityUpsert) {
		s.ClearAvatar()
	})
}

// Exec executes the query.
func (u *UserIdentityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserIdentityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserIdentityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserIdentityUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserIdentityUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (m *UserIdentityCreate) SetRawID(t int) *UserIdentityCreate {
	m.mutation.SetRawID(t)
	return m
}

// UserIdentityCreateBulk is the builder for creating many UserIdentity entities in bulk.
type UserIdentityCreateBulk struct {
	config
	err      error
	builders []*UserIdentityCreate
	conflict []sql.ConflictOption
}

// Save creates the UserIdentity entities in the database.
func (uicb *UserIdentityCreateBulk) Save(ctx context.Context) ([]*UserIdentity, error) {
	if uicb.err != nil {
		return nil, uicb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(uicb.builders))
	nodes := make([]*UserIdentity, len(uicb.builders))
	mutators := make([]Mutator, len(uicb.builders))
	for i := range uicb.builders {
		func(i int, root context.Context) {
			builder := uicb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserIdentityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = uicb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uicb *UserIdentityCreateBulk) SaveX(ctx context.Context) []*UserIdentity {
	v, err := uicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uicb *UserIdentityCreateBulk) Exec(ctx context.Context) error {
	_, err := uicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uicb *UserIdentityCreateBulk) ExecX(ctx context.Context) {
	if err := uicb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserIdentity.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserIdentityUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (uicb *UserIdentityCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserIdentityUpsertBulk {
	uicb.conflict = opts
	return &UserIdentityUpsertBulk{
		create: uicb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserIdentity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (uicb *UserIdentityCreateBulk) OnConflictColumns(columns ...string) *UserIdentityUpsertBulk {
	uicb.conflict = append(uicb.conflict, sql.ConflictColumns(columns...))
	return &UserIdentityUpsertBulk{
		create: uicb,
	}
}

// UserIdentityUpsertBulk is the builder for "upsert"-ing
// a bulk of UserIdentity nodes.
type UserIdentityUpsertBulk struct {
	create *UserIdentityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserIdentity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserIdentityUpsertBulk) UpdateNewValues() *UserIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(useridentity.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserIdentity.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserIdentityUpsertBulk) Ignore() *UserIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserIdentityUpsertBulk) DoNothing() *UserIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserIdentityCreateBulk.OnConflict
// documentation for more info.
func (u *UserIdentityUpsertBulk) Update(set func(*UserIdentityUpsert)) *UserIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserIdentityUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserIdentityUpsertBulk) SetUpdatedAt(v time.Time) *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserIdentityUpsertBulk) UpdateUpdatedAt() *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserIdentityUpsertBulk) SetDeletedAt(v time.Time) *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserIdentityUpsertBulk) UpdateDeletedAt() *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserIdentityUpsertBulk) ClearDeletedAt() *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserIdentityUpsertBulk) SetUserID(v int) *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserIdentityUpsertBulk) UpdateUserID() *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.UpdateUserID()
	})
}

// SetProvider sets the "provider" field.
func (u *UserIdentityUpsertBulk) SetProvider(v string) *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *UserIdentityUpsertBulk) UpdateProvider() *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.UpdateProvider()
	})
}

// SetIssuer sets the "issuer" field.
func (u *UserIdentityUpsertBulk) SetIssuer(v string) *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.SetIssuer(v)
	})
}

// UpdateIssuer sets the "issuer" field to the value that was provided on create.
func (u *UserIdentityUpsertBulk) UpdateIssuer() *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.UpdateIssuer()
	})
}

// SetSubject sets the "subject" field.
func (u *UserIdentityUpsertBulk) SetSubject(v string) *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *UserIdentityUpsertBulk) UpdateSubject() *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.UpdateSubject()
	})
}

// SetEmail sets the "email" field.
func (u *UserIdentityUpsertBulk) SetEmail(v string) *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *UserIdentityUpsertBulk) UpdateEmail() *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.UpdateEmail()
	})
}

// ClearEmail clears the value of the "email" field.
func (u *UserIdentityUpsertBulk) ClearEmail() *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.ClearEmail()
	})
}

// SetEmailVerified sets the "email_verified" field.
func (u *UserIdentityUpsertBulk) SetEmailVerified(v bool) *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.SetEmailVerified(v)
	})
}

// UpdateEmailVerified sets the "email_verified" field to the value that was provided on create.
func (u *UserIdentityUpsertBulk) UpdateEmailVerified() *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.UpdateEmailVerified()
	})
}

// SetName sets the "name" field.
func (u *UserIdentityUpsertBulk) SetName(v string) *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UserIdentityUpsertBulk) UpdateName() *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *UserIdentityUpsertBulk) ClearName() *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.ClearName()
	})
}

// SetAvatar sets the "avatar" field.
func (u *UserIdentityUpsertBulk) SetAvatar(v string) *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.SetAvatar(v)
	})
}

// UpdateAvatar sets the "avatar" field to the value that was provided on create.
func (u *UserIdentityUpsertBulk) UpdateAvatar() *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.UpdateAvatar()
	})
}

// ClearAvatar clears the value of the "avatar" field.
func (u *UserIdentityUpsertBulk) ClearAvatar() *UserIdentityUpsertBulk {
	return u.Update(func(s *UserIdentityUpsert) {
		s.ClearAvatar()
	})
}

// Exec executes the query.
func (u *UserIdentityUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserIdentityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserIdentityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserIdentityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
