// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
	"github.com/cloudreve/Cloudreve/v4/ent/useridentity"
)

// UserIdentityUpdate is the builder for updating UserIdentity entities.
type UserIdentityUpdate struct {
	config
	hooks    []Hook
	mutation *UserIdentityMutation
}

// Where appends a list predicates to the UserIdentityUpdate builder.
func (uiu *UserIdentityUpdate) Where(ps ...predicate.UserIdentity) *UserIdentityUpdate {
	uiu.mutation.Where(ps...)
	return uiu
}

// SetUpdatedAt sets the "updated_at" field.
func (uiu *UserIdentityUpdate) SetUpdatedAt(t time.Time) *UserIdentityUpdate {
	uiu.mutation.SetUpdatedAt(t)
	return uiu
}

// SetDeletedAt sets the "deleted_at" field.
func (uiu *UserIdentityUpdate) SetDeletedAt(t time.Time) *UserIdentityUpdate {
	uiu.mutation.SetDeletedAt(t)
	return uiu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (uiu *UserIdentityUpdate) SetNillableDeletedAt(t *time.Time) *UserIdentityUpdate {
	if t != nil {
		uiu.SetDeletedAt(*t)
	}
	return uiu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (uiu *UserIdentityUpdate) ClearDeletedAt() *UserIdentityUpdate {
	uiu.mutation.ClearDeletedAt()
	return uiu
}

// SetUserID sets the "user_id" field.
func (uiu *UserIdentityUpdate) SetUserID(i int) *UserIdentityUpdate {
	uiu.mutation.SetUserID(i)
	return uiu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (uiu *UserIdentityUpdate) SetNillableUserID(i *int) *UserIdentityUpdate {
	if i != nil {
		uiu.SetUserID(*i)
	}
	return uiu
}

// SetProvider sets the "provider" field.
func (uiu *UserIdentityUpdate) SetProvider(s string) *UserIdentityUpdate {
	uiu.mutation.SetProvider(s)
	return uiu
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (uiu *UserIdentityUpdate) SetNillableProvider(s *string) *UserIdentityUpdate {
	if s != nil {
		uiu.SetProvider(*s)
	}
	return uiu
}

// SetIssuer sets the "issuer" field.
func (uiu *UserIdentityUpdate) SetIssuer(s string) *UserIdentityUpdate {
	uiu.mutation.SetIssuer(s)
	return uiu
}

// SetNillableIssuer sets the "issuer" field if the given value is not nil.
func (uiu *UserIdentityUpdate) SetNillableIssuer(s *string) *UserIdentityUpdate {
	if s != nil {
		uiu.SetIssuer(*s)
	}
	return uiu
}

// SetSubject sets the "subject" field.
func (uiu *UserIdentityUpdate) SetSubject(s string) *UserIdentityUpdate {
	uiu.mutation.SetSubject(s)
	return uiu
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (uiu *UserIdentityUpdate) SetNillableSubject(s *string) *UserIdentityUpdate {
	if s != nil {
		uiu.SetSubject(*s)
	}
	return uiu
}

// SetEmail sets the "email" field.
func (uiu *UserIdentityUpdate) SetEmail(s string) *UserIdentityUpdate {
	uiu.mutation.SetEmail(s)
	return uiu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (uiu *UserIdentityUpdate) SetNillableEmail(s *string) *UserIdentityUpdate {
	if s != nil {
		uiu.SetEmail(*s)
	}
	return uiu
}

// ClearEmail clears the value of the "email" field.
func (uiu *UserIdentityUpdate) ClearEmail() *UserIdentityUpdate {
	uiu.mutation.ClearEmail()
	return uiu
}

// SetEmailVerified sets the "email_verified" field.
func (uiu *UserIdentityUpdate) SetEmailVerified(b bool) *UserIdentityUpdate {
	uiu.mutation.SetEmailVerified(b)
	return uiu
}

// SetNillableEmailVerified sets the "email_verified" field if the given value is not nil.
func (uiu *UserIdentityUpdate) SetNillableEmailVerified(b *bool) *UserIdentityUpdate {
	if b != nil {
		uiu.SetEmailVerified(*b)
	}
	return uiu
}

// SetName sets the "name" field.
func (uiu *UserIdentityUpdate) SetName(s string) *UserIdentityUpdate {
	uiu.mutation.SetName(s)
	return uiu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (uiu *UserIdentityUpdate) SetNillableName(s *string) *UserIdentityUpdate {
	if s != nil {
		uiu.SetName(*s)
	}
	return uiu
}

// ClearName clears the value of the "name" field.
func (uiu *UserIdentityUpdate) ClearName() *UserIdentityUpdate {
	uiu.mutation.ClearName()
	return uiu
}

// SetAvatar sets the "avatar" field.
func (uiu *UserIdentityUpdate) SetAvatar(s string) *UserIdentityUpdate {
	uiu.mutation.SetAvatar(s)
	return uiu
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (uiu *UserIdentityUpdate) SetNillableAvatar(s *string) *UserIdentityUpdate {
	if s != nil {
		uiu.SetAvatar(*s)
	}
	return uiu
}

// ClearAvatar clears the value of the "avatar" field.
func (uiu *UserIdentityUpdate) ClearAvatar() *UserIdentityUpdate {
	uiu.mutation.ClearAvatar()
	return uiu
}

// SetUser sets the "user" edge to the User entity.
func (uiu *UserIdentityUpdate) SetUser(u *User) *UserIdentityUpdate {
	return uiu.SetUserID(u.ID)
}

// Mutation returns the UserIdentityMutation object of the builder.
func (uiu *UserIdentityUpdate) Mutation() *UserIdentityMutation {
	return uiu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (uiu *UserIdentityUpdate) ClearUser() *UserIdentityUpdate {
	uiu.mutation.ClearUser()
	return uiu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uiu *UserIdentityUpdate) Save(ctx context.Context) (int, error) {
	if err := uiu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, uiu.sqlSave, uiu.mutation, uiu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uiu *UserIdentityUpdate) SaveX(ctx context.Context) int {
	affected, err := uiu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uiu *UserIdentityUpdate) Exec(ctx context.Context) error {
	_, err := uiu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uiu *UserIdentityUpdate) ExecX(ctx context.Context) {
	if err := uiu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uiu *UserIdentityUpdate) defaults() error {
	if _, ok := uiu.mutation.UpdatedAt(); !ok {
		if useridentity.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized useridentity.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := useridentity.UpdateDefaultUpdatedAt()
		uiu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (uiu *UserIdentityUpdate) check() error {
	if _, ok := uiu.mutation.UserID(); uiu.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UserIdentity.user"`)
	}
	return nil
}

func (uiu *UserIdentityUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := uiu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(useridentity.Table, useridentity.Columns, sqlgraph.NewFieldSpec(useridentity.FieldID, field.TypeInt))
	if ps := uiu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uiu.mutation.UpdatedAt(); ok {
		_spec.SetField(useridentity.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := uiu.mutation.DeletedAt(); ok {
		_spec.SetField(useridentity.FieldDeletedAt, field.TypeTime, value)
	}
	if uiu.mutation.DeletedAtCleared() {
		_spec.ClearField(useridentity.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := uiu.mutation.Provider(); ok {
		_spec.SetField(useridentity.FieldProvider, field.TypeString, value)
	}
	if value, ok := uiu.mutation.Issuer(); ok {
		_spec.SetField(useridentity.FieldIssuer, field.TypeString, value)
	}
	if value, ok := uiu.mutation.Subject(); ok {
		_spec.SetField(useridentity.FieldSubject, field.TypeString, value)
	}
	if value, ok := uiu.mutation.Email(); ok {
		_spec.SetField(useridentity.FieldEmail, field.TypeString, value)
	}
	if uiu.mutation.EmailCleared() {
		_spec.ClearField(useridentity.FieldEmail, field.TypeString)
	}
	if value, ok := uiu.mutation.EmailVerified(); ok {
		_spec.SetField(useridentity.FieldEmailVerified, field.TypeBool, value)
	}
	if value, ok := uiu.mutation.Name(); ok {
		_spec.SetField(useridentity.FieldName, field.TypeString, value)
	}
	if uiu.mutation.NameCleared() {
		_spec.ClearField(useridentity.FieldName, field.TypeString)
	}
	if value, ok := uiu.mutation.Avatar(); ok {
		_spec.SetField(useridentity.FieldAvatar, field.TypeString, value)
	}
	if uiu.mutation.AvatarCleared() {
		_spec.ClearField(useridentity.FieldAvatar, field.TypeString)
	}
	if uiu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useridentity.UserTable,
			Columns: []string{useridentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uiu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useridentity.UserTable,
			Columns: []string{useridentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uiu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useridentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uiu.mutation.done = true
	return n, nil
}

// UserIdentityUpdateOne is the builder for updating a single UserIdentity entity.
type UserIdentityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserIdentityMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (uiuo *UserIdentityUpdateOne) SetUpdatedAt(t time.Time) *UserIdentityUpdateOne {
	uiuo.mutation.SetUpdatedAt(t)
	return uiuo
}

// SetDeletedAt sets the "deleted_at" field.
func (uiuo *UserIdentityUpdateOne) SetDeletedAt(t time.Time) *UserIdentityUpdateOne {
	uiuo.mutation.SetDeletedAt(t)
	return uiuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (uiuo *UserIdentityUpdateOne) SetNillableDeletedAt(t *time.Time) *UserIdentityUpdateOne {
	if t != nil {
		uiuo.SetDeletedAt(*t)
	}
	return uiuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (uiuo *UserIdentityUpdateOne) ClearDeletedAt() *UserIdentityUpdateOne {
	uiuo.mutation.ClearDeletedAt()
	return uiuo
}

// SetUserID sets the "user_id" field.
func (uiuo *UserIdentityUpdateOne) SetUserID(i int) *UserIdentityUpdateOne {
	uiuo.mutation.SetUserID(i)
	return uiuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (uiuo *UserIdentityUpdateOne) SetNillableUserID(i *int) *UserIdentityUpdateOne {
	if i != nil {
		uiuo.SetUserID(*i)
	}
	return uiuo
}

// SetProvider sets the "provider" field.
func (uiuo *UserIdentityUpdateOne) SetProvider(s string) *UserIdentityUpdateOne {
	uiuo.mutation.SetProvider(s)
	return uiuo
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (uiuo *UserIdentityUpdateOne) SetNillableProvider(s *string) *UserIdentityUpdateOne {
	if s != nil {
		uiuo.SetProvider(*s)
	}
	return uiuo
}

// SetIssuer sets the "issuer" field.
func (uiuo *UserIdentityUpdateOne) SetIssuer(s string) *UserIdentityUpdateOne {
	uiuo.mutation.SetIssuer(s)
	return uiuo
}

// SetNillableIssuer sets the "issuer" field if the given value is not nil.
func (uiuo *UserIdentityUpdateOne) SetNillableIssuer(s *string) *UserIdentityUpdateOne {
	if s != nil {
		uiuo.SetIssuer(*s)
	}
	return uiuo
}

// SetSubject sets the "subject" field.
func (uiuo *UserIdentityUpdateOne) SetSubject(s string) *UserIdentityUpdateOne {
	uiuo.mutation.SetSubject(s)
	return uiuo
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (uiuo *UserIdentityUpdateOne) SetNillableSubject(s *string) *UserIdentityUpdateOne {
	if s != nil {
		uiuo.SetSubject(*s)
	}
	return uiuo
}

// SetEmail sets the "email" field.
func (uiuo *UserIdentityUpdateOne) SetEmail(s string) *UserIdentityUpdateOne {
	uiuo.mutation.SetEmail(s)
	return uiuo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (uiuo *UserIdentityUpdateOne) SetNillableEmail(s *string) *UserIdentityUpdateOne {
	if s != nil {
		uiuo.SetEmail(*s)
	}
	return uiuo
}

// ClearEmail clears the value of the "email" field.
func (uiuo *UserIdentityUpdateOne) ClearEmail() *UserIdentityUpdateOne {
	uiuo.mutation.ClearEmail()
	return uiuo
}

// SetEmailVerified sets the "email_verified" field.
func (uiuo *UserIdentityUpdateOne) SetEmailVerified(b bool) *UserIdentityUpdateOne {
	uiuo.mutation.SetEmailVerified(b)
	return uiuo
}

// SetNillableEmailVerified sets the "email_verified" field if the given value is not nil.
func (uiuo *UserIdentityUpdateOne) SetNillableEmailVerified(b *bool) *UserIdentityUpdateOne {
	if b != nil {
		uiuo.SetEmailVerified(*b)
	}
	return uiuo
}

// SetName sets the "name" field.
func (uiuo *UserIdentityUpdateOne) SetName(s string) *UserIdentityUpdateOne {
	uiuo.mutation.SetName(s)
	return uiuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (uiuo *UserIdentityUpdateOne) SetNillableName(s *string) *UserIdentityUpdateOne {
	if s != nil {
		uiuo.SetName(*s)
	}
	return uiuo
}

// ClearName clears the value of the "name" field.
func (uiuo *UserIdentityUpdateOne) ClearName() *UserIdentityUpdateOne {
	uiuo.mutation.ClearName()
	return uiuo
}

// SetAvatar sets the "avatar" field.
func (uiuo *UserIdentityUpdateOne) SetAvatar(s string) *UserIdentityUpdateOne {
	uiuo.mutation.SetAvatar(s)
	return uiuo
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (uiuo *UserIdentityUpdateOne) SetNillableAvatar(s *string) *UserIdentityUpdateOne {
	if s != nil {
		uiuo.SetAvatar(*s)
	}
	return uiuo
}

// ClearAvatar clears the value of the "avatar" field.
func (uiuo *UserIdentityUpdateOne) ClearAvatar() *UserIdentityUpdateOne {
	uiuo.mutation.ClearAvatar()
	return uiuo
}

// SetUser sets the "user" edge to the User entity.
func (uiuo *UserIdentityUpdateOne) SetUser(u *User) *UserIdentityUpdateOne {
	return uiuo.SetUserID(u.ID)
}

// Mutation returns the UserIdentityMutation object of the builder.
func (uiuo *UserIdentityUpdateOne) Mutation() *UserIdentityMutation {
	return uiuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (uiuo *UserIdentityUpdateOne) ClearUser() *UserIdentityUpdateOne {
	uiuo.mutation.ClearUser()
	return uiuo
}

// Where appends a list predicates to the UserIdentityUpdate builder.
func (uiuo *UserIdentityUpdateOne) Where(ps ...predicate.UserIdentity) *UserIdentityUpdateOne {
	uiuo.mutation.Where(ps...)
	return uiuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uiuo *UserIdentityUpdateOne) Select(field string, fields ...string) *UserIdentityUpdateOne {
	uiuo.fields = append([]string{field}, fields...)
	return uiuo
}

// Save executes the query and returns the updated UserIdentity entity.
func (uiuo *UserIdentityUpdateOne) Save(ctx context.Context) (*UserIdentity, error) {
	if err := uiuo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, uiuo.sqlSave, uiuo.mutation, uiuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uiuo *UserIdentityUpdateOne) SaveX(ctx context.Context) *UserIdentity {
	node, err := uiuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uiuo *UserIdentityUpdateOne) Exec(ctx context.Context) error {
	_, err := uiuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uiuo *UserIdentityUpdateOne) ExecX(ctx context.Context) {
	if err := uiuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uiuo *UserIdentityUpdateOne) defaults() error {
	if _, ok := uiuo.mutation.UpdatedAt(); !ok {
		if useridentity.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized useridentity.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := useridentity.UpdateDefaultUpdatedAt()
		uiuo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (uiuo *UserIdentityUpdateOne) check() error {
	if _, ok := uiuo.mutation.UserID(); uiuo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UserIdentity.user"`)
	}
	return nil
}

func (uiuo *UserIdentityUpdateOne) sqlSave(ctx context.Context) (_node *UserIdentity, err error) {
	if err := uiuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useridentity.Table, useridentity.Columns, sqlgraph.NewFieldSpec(useridentity.FieldID, field.TypeInt))
	id, ok := uiuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserIdentity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uiuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useridentity.FieldID)
		for _, f := range fields {
			if !useridentity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useridentity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uiuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uiuo.mutation.UpdatedAt(); ok {
		_spec.SetField(useridentity.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := uiuo.mutation.DeletedAt(); ok {
		_spec.SetField(useridentity.FieldDeletedAt, field.TypeTime, value)
	}
	if uiuo.mutation.DeletedAtCleared() {
		_spec.ClearField(useridentity.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := uiuo.mutation.Provider(); ok {
		_spec.SetField(useridentity.FieldProvider, field.TypeString, value)
	}
	if value, ok := uiuo.mutation.Issuer(); ok {
		_spec.SetField(useridentity.FieldIssuer, field.TypeString, value)
	}
	if value, ok := uiuo.mutation.Subject(); ok {
		_spec.SetField(useridentity.FieldSubject, field.TypeString, value)
	}
	if value, ok := uiuo.mutation.Email(); ok {
		_spec.SetField(useridentity.FieldEmail, field.TypeString, value)
	}
	if uiuo.mutation.EmailCleared() {
		_spec.ClearField(useridentity.FieldEmail, field.TypeString)
	}
	if value, ok := uiuo.mutation.EmailVerified(); ok {
		_spec.SetField(useridentity.FieldEmailVerified, field.TypeBool, value)
	}
	if value, ok := uiuo.mutation.Name(); ok {
		_spec.SetField(useridentity.FieldName, field.TypeString, value)
	}
	if uiuo.mutation.NameCleared() {
		_spec.ClearField(useridentity.FieldName, field.TypeString)
	}
	if value, ok := uiuo.mutation.Avatar(); ok {
		_spec.SetField(useridentity.FieldAvatar, field.TypeString, value)
	}
	if uiuo.mutation.AvatarCleared() {
		_spec.ClearField(useridentity.FieldAvatar, field.TypeString)
	}
	if uiuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useridentity.UserTable,
			Columns: []string{useridentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uiuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useridentity.UserTable,
			Columns: []string{useridentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserIdentity{config: uiuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uiuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useridentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uiuo.mutation.done = true
	return _node, nil
}
